In [15]:
import numpy as np #LAB 11-1(1)

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
import numpy as np #LAB11-1(2)

b = np.array(list(range(0, 10)))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
import numpy as np #LAB11-1(3)

c = np.array(list(range(0, 10, 2)))
c

array([0, 2, 4, 6, 8])

In [13]:
import numpy as np #LAB11-1(4)

c = np.array(list(range(0, 10, 2)), dtype = 'int64')

print('c.shape =', c.shape)
print('c.ndim =', c.ndim)
print('c.dtype =', c.dtype)
print('c.size =', c.size)
print('c.itemsize =', c.itemsize)


c.shape = (5,)
c.ndim = 1
c.dtype = int64
c.size = 5
c.itemsize = 8


In [59]:
import numpy as np #LAB11-2
import random

a = np.array([23, 45, 67, 7, 2, 30, 34, 82])
print('a = array(', a, ')')

print()
print('최댓값 :', a.max())
print('최솟값 :', a.min())
print('평균 :', a.mean())

print()
b = np.random.randint(0, 100, size = 10)
print('b =', b)
print('최댓값 :', b.max())
print('최솟값 :', b.min())
print('평균 :', b.mean())

print()
c = np.append(a, b)
print('c =', c)

a = array( [23 45 67  7  2 30 34 82] )

최댓값 : 82
최솟값 : 2
평균 : 36.25

b = [25 13 79  2 88 71 60 90 20 26]
최댓값 : 90
최솟값 : 2
평균 : 47.4

c = [23 45 67  7  2 30 34 82 25 13 79  2 88 71 60 90 20 26]


In [44]:
import numpy as np #LAB11-3

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('a =', a)

b = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
print('b =', b)

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a @ b)
print(a ** b)

a = [[1 2 3]
 [4 5 6]
 [7 8 9]]
b = [[2 2 2]
 [2 2 2]
 [2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[12 12 12]
 [30 30 30]
 [48 48 48]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [49]:
import numpy as np #LAB11-4

a1 = np.full((3, 3), 2)
print('a1 =', a1)

print()
a2 = np.arange(1, 13)
print('a2 =', a2)

print()
a3 = np.arange(0, 51, 3)
print('a3 =', a3)

print()
a4 = np.linspace(0, 20, 5)
print('a4 =', a4)



a1 = [[2 2 2]
 [2 2 2]
 [2 2 2]]

a2 = [ 1  2  3  4  5  6  7  8  9 10 11 12]

a3 = [ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]

a4 = [ 0.  5. 10. 15. 20.]


In [54]:
import numpy as np #LAB11-5

a1 = np.arange(1, 13)
print('a1 =', a1.reshape(2, 6))

print()
a2 = np.arange(1, 31)
print('a2 =', a2.reshape(3, 10))

print()
a3 = a2.reshape(6, 5)
print('a3 =', a3)

print()
a4 = np.transpose(a3)
print('a4 =', a4)




a1 = [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

a2 = [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

a3 = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

a4 = [[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


In [57]:
import numpy as np #LAB11-6              
import random

a = np.random.randint(1, 101, size = 15).reshape(3, 5)
print('a =', a)

print()
print('a의 열방향 최댓값 :', a.max(axis = 0))
print('a의 열방향 최솟값 :', a.min(axis = 0))
print('a의 열방향 평균 :', a.mean(axis = 0))

print()
print('a의 행방향 최댓값 :', a.max(axis = 1))
print('a의 행방향 최솟값 :', a.min(axis = 1))
print('a의 행방향 평균 :', a.mean(axis = 1))

a = [[ 8 90 62 80 33]
 [ 7 37 27 52 66]
 [35 39 86 82 77]]

a의 열방향 최댓값 : [35 90 86 82 77]
a의 열방향 최솟값 : [ 7 37 27 52 33]
a의 열방향 평균 : [16.66666667 55.33333333 58.33333333 71.33333333 58.66666667]

a의 행방향 최댓값 : [90 66 86]
a의 행방향 최솟값 : [ 8  7 35]
a의 행방향 평균 : [54.6 37.8 63.8]


In [64]:
import numpy as np #LAB11-7

a = np.arange(1, 11)
b = a[1:9:2]
print('a =', a)
print('b =', b)

print()
b = a[5:10]
c = a[6:10]
d = a[0:3]
e = a[0:10:2]
f = a[::-2]
print('b =', b)
print('c =', c)
print('d =', d)
print('e =', e)
print('f =', f)


a = [ 1  2  3  4  5  6  7  8  9 10]
b = [2 4 6 8]

b = [ 6  7  8  9 10]
c = [ 7  8  9 10]
d = [1 2 3]
e = [1 3 5 7 9]
f = [10  8  6  4  2]


In [85]:
import numpy as np #LAB11-8

print('index     element')
a = np.arange(0, 24).reshape(4, 3, 2)
for i in range(4):
    for j in range(3):
        for k in range(2):
            print('({}, {}, {})   {}'.format(i, j, k, a[i][j][k]))

print()
print(repr(np.concatenate((a[0, 0], a[1, 0]), axis = 0)))

print()
print(repr(np.concatenate((a[0, 0], a[2, 1]), axis = 0)))

print()
print(repr(np.concatenate((a[0, 0], a[0, 1], a[0, 2], a[1, 0], a[1, 1], a[1, 2]), axis = 0).reshape(6, 2)))
    
print()
print(repr(np.concatenate((a[0, 0], a[1, 0], a[0, 1], a[1, 1], a[0, 2], a[1, 2]), axis = 0).reshape(3, 4)))

index     element
(0, 0, 0)   0
(0, 0, 1)   1
(0, 1, 0)   2
(0, 1, 1)   3
(0, 2, 0)   4
(0, 2, 1)   5
(1, 0, 0)   6
(1, 0, 1)   7
(1, 1, 0)   8
(1, 1, 1)   9
(1, 2, 0)   10
(1, 2, 1)   11
(2, 0, 0)   12
(2, 0, 1)   13
(2, 1, 0)   14
(2, 1, 1)   15
(2, 2, 0)   16
(2, 2, 1)   17
(3, 0, 0)   18
(3, 0, 1)   19
(3, 1, 0)   20
(3, 1, 1)   21
(3, 2, 0)   22
(3, 2, 1)   23

array([0, 1, 6, 7])

array([ 0,  1, 14, 15])

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])


In [93]:
import numpy as np #LAB11-9

a = np.arange(0, 16).reshape(4, 4)
b = a[:, 1]
c = a[2, 1:]
d = a[0:2, 0:2]
e = a[1:3, 1:3]
print('b =', b)
print('c =', c)
print('d =', d)
print('e =', e)

print()
f = a[0:2, 0:3].flatten()
g = a[2:4, 0:4].flatten()
h = a[1:4:2, 1:4].flatten()
print('f =', f)
print('g =', g)
print('h =', h)


b = [ 1  5  9 13]
c = [ 9 10 11]
d = [[0 1]
 [4 5]]
e = [[ 5  6]
 [ 9 10]]

f = [0 1 2 4 5 6]
g = [ 8  9 10 11 12 13 14 15]
h = [ 5  6  7 13 14 15]


In [8]:
import numpy as np #LAB11-10

a = np.array([[1, 1, -1], [2, -1, 3], [1, 2, 1]])
b = np.array([0, 9, 8])

x = np.linalg.solve(a, b)
print('x = {}, y = {}, z = {}'.format(round(x[0], 0), round(x[1], 0), round(x[2], 0)))

x = 1.0, y = 2.0, z = 3.0
